sudo: false
# dist: trusty

language: python

python:
  - 2.7
  - 3.4

# branches:
#   only:
#    - master
#
# services:
#
# matrix:
#  include:
#    - os: linux

install:
  - pip install -U pytest
  - pip install pytest-cov
  - pip install Pillow
  - python setup.py install  

script:
  - pytest -v --cov

after_success:
  - codecov
  
notifications:
  email:
    on_success: change
    on_failure: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6b9d6dacd08d3e45e1b3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
